services:

  php-fpm:
    environment:
      PHP_OPCACHE_ENABLE: 1

  sql:
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    ports:
      - "127.0.0.1:6379:6379"

  nginx:
    build:
      dockerfile: prod/Dockerfile
    ports:
      - "443:443"
      - "80:80"
