version: "3"

services:

  php-fpm:
    environment:
      - PHP_OPCACHE_ENABLE=${PHP_OPCACHE:-0}

  nginx:
    build:
      dockerfile: local/Dockerfile
    ports:
      - "8080:443"

  sql:
    ports:
      - "54321:5432"

  selenium:
    image: 'selenium/standalone-chrome:latest'
    volumes:
      - '/dev/shm:/dev/shm'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
